#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 10 09:32:34 2020

@author: ravinderjit

Calculate system functions from EEG data for Dynamic Binaural Msequence project
"""

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import scipy.io as sio
import os
import pickle
import numpy as np
import scipy as sp
from anlffr.spectral import mtspecraw
from spectralAnalysis import periodogram
# import mne

direct_Mseq = '/media/ravinderjit/Data_Drive/Data/EEGdata/DynamicBinaural/Mseq_4096fs_compensated.mat'
data_loc = os.path.abspath('/media/ravinderjit/Data_Drive/Data/EEGdata/DynamicBinaural/Pickles')

Mseq_mat = sio.loadmat(direct_Mseq)
Mseq = Mseq_mat['Mseq_sig'].T
Mseq = Mseq.astype(float)

Num_noiseFloors = 50
Keep_H = 1 #length of system function to keep in seconds 

Subjects = ['S001','S132','S203','S204','S205','S206','S207','S208','S211']
Subject = Subjects[6]

with open(os.path.join(data_loc, Subject+'_DynBin.pickle'),'rb') as f:
    IAC_epochs, ITD_epochs = pickle.load(f)

t = IAC_epochs.times
fs = IAC_epochs.info['sfreq']
IAC32 = IAC_epochs.get_data()
ITD32 = ITD_epochs.get_data()
IAC32 = IAC32.T[:,0,:]
ITD32 = ITD32.T[:,0,:]

#%% Plot PSD, should be clear ASSR at 20 Hz
IAC_epochs.plot_psd(fmin=0, fmax=50, tmin = 0.0, tmax=12.75, proj=True,average=False)
ITD_epochs.plot_psd(fmin=0, fmax=50, tmin = 0.0, tmax=12.75, proj=True,average=False)

#%% Remove any epochs with large deflections
Peak2Peak_IAC = IAC32.max(axis=0) - IAC32.min(axis=0)
IAC32 = IAC32[:,Peak2Peak_IAC*1e6 < 100.]
Peak2Peak_ITD =ITD32.max(axis=0) - ITD32.min(axis=0)
ITD32 = ITD32[:,Peak2Peak_ITD*1e6 < 100.]

#%% visualize epochs
plt.figure()
plt.plot(t,IAC32*1e6)
plt.plot(t,IAC32.mean(axis=1)*1e6,linewidth=3,color='k')
plt.title('IAC')
plt.figure()
plt.plot(t,ITD32*1e6)
plt.plot(t,ITD32.mean(axis=1)*1e6,linewidth=3,color='k')
plt.title('ITD')

#%% Extract part of response when stim is on
t1 = np.where(t>=0)[0][0]
t2 = np.where(t>=12.75)[0][0]
t = t[t1:t2]
IAC32 = IAC32[t1:t2,:]
ITD32 = ITD32[t1:t2,:]

#%% Generate Noise Floors
# Generated by subtracting half of epochs from each other
IAC_nfs = np.zeros([Num_noiseFloors,Mseq.size])
ITD_nfs = np.zeros([Num_noiseFloors,Mseq.size])
for nn in range(0,Num_noiseFloors):
    randInds = np.random.permutation(IAC32.shape[1]) #random inds for epochs
    IAC_Noise = (IAC32[:, randInds[0:int(np.round(randInds.size/2))]].sum(axis=1) - \
                 IAC32[:, randInds[int(np.round(randInds.size/2)):]].sum(axis=1)) / randInds.size
    
    randInds = np.random.permutation(ITD32.shape[1])
    ITD_Noise = (ITD32[:, randInds[0:int(np.round(randInds.size/2))]].sum(axis=1) - \
        ITD32[:, randInds[int(np.round(randInds.size/2)):]].sum(axis=1)) / randInds.size
    
    IAC_nf = np.correlate(IAC_Noise,Mseq[:,0],mode='full')
    IAC_nfs[nn,:] = IAC_nf[Mseq.size-1:]
    
    ITD_nf = np.correlate(ITD_Noise,Mseq[:,0],mode='full')
    ITD_nfs[nn,:] = ITD_nf[Mseq.size-1:]
    
#%% Calculate Ht
IAC_Ht = np.correlate(IAC32.mean(axis=1),Mseq[:,0],mode='full')
IAC_Ht = IAC_Ht[Mseq.size-1:]

plt.figure()
plt.plot(t,IAC_nfs.T,color= mcolors.CSS4_COLORS['grey'])
plt.plot(t,IAC_Ht,color='k')
plt.xlim([0,Keep_H])

#%% Calculate Hf
params = {'Fs':fs, 'tapers':[1.5,2], 'fpass':[0,40]}
IAC_getHf = IAC_Ht[:int(np.round(Keep_H*fs))]
IAC_getHf = IAC_getHf.reshape([1,IAC_getHf.size])

out_IAC = mtspecraw(IAC_getHf,params)
IAC_Hf = 10*np.log10(out_IAC[0])
f = out_IAC[1]

NF_Hfs = np.zeros([Num_noiseFloors,IAC_Hf.size])
for j in range(0,Num_noiseFloors):
    NF_getHf = IAC_nfs[j,:int(np.round(Keep_H*fs))]
    NF_getHf = NF_getHf.reshape([1,NF_getHf.size])
    out_NF = mtspecraw(NF_getHf,params)
    NF_Hfs[j,:] = 10*np.log10(out_NF[0])

fig = plt.figure()
plt.plot(f,IAC_Hf)
plt.plot(f,NF_Hfs.T,color= mcolors.CSS4_COLORS['grey'])
fig.axes[0].set_xscale('log')
plt.xlim([0,20])


#%% Calculate TMTF via PLV


# Mf = sp.fft(Mseq,axis=0,n=N)
# Yf = sp.fft(IAC32.mean(axis=1),axis=0,n=N)
# f = np.arange(0,N)*fs/N
TW = 4 #time half bandwidth product
ntaps = 2*TW -1 
dpss = sp.signal.windows.dpss(Mseq.size,TW,ntaps)

N = int(2**np.ceil(np.log2(Mseq.size)))
Mf = np.zeros([Mseq.size])

for k in range(0,ntaps):
    window = dpss[k,:]
    Mf[k,:] += sp.fft(Mseq[:,0]*window,axis=0,n=N) / ntaps
    
    


plt.figure()
plt.plot(f,abs(Mf)**2)







    
    
    
    














